### ISSUE TITLE
GPS testing using different mobile devices

### ISSUE THREAD

**Issue by ZoeUdy** [FrancisG-Massey/Capstone2016#140]

**Comment by ZoeUdy** [comment]
More testing could be useful, however, there is not time before the final submission

**Comment by samhunt0** [comment]
@FrancisG-Massey mentioned that the app uses the **_location service_** rather than explicitly using **_GPS_** right?
  
As was the case with his device, if there's no GPS, there may still be a **location service**, and the App will try to use this, but the hardware implementation will be reverting back to using cell-phone tower signals or wifi-signals or whatever in an attempt to triangulate the position under the hood thus resulting in the inaccurate map results in the above screenshot.

@ZoeUdy If this is actually the case, then this shouldn't even really be classified as a GPS problem, and I think we should make this distinction clearly when we discuss the limitations of the App. Because, as we **_have_** proven through testing, the GPS is not this inaccurate in most cases where a device actually has a GPS unit.
